services:
  postgres:
    image: postgres:15
    container_name: buyora_postgres
    environment:
      POSTGRES_DB: buyora_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ravi@515241
    ports:
      - "5433:5432"
